name: cwa-windows

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  cwa-windows:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Compile java files
        run: |
          java -version
          javac src\actipy\*.java

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install pytest joblib

      - name: Download test file
        run: |
          mkdir tests\data
          curl --output-dir tests\data\ -O https://wearables-files.ndph.ox.ac.uk/files/data/samples/ax3/tiny-sample.cwa.gz
          curl --output-dir tests\data\ -O https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/read.pkl.gz
          curl --output-dir tests\data\ -O https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/lowpass.pkl.gz
          curl --output-dir tests\data\ -O https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/calib.pkl.gz
          curl --output-dir tests\data\ -O https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/nonwear.pkl.gz
          curl --output-dir tests\data\ -O https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/resample.pkl.gz
          copy tests\data\tiny-sample.cwa.gz tests\data\tiny-sample1.cwa.gz  # make copies for multiprocessing test
          copy tests\data\tiny-sample.cwa.gz tests\data\tiny-sample2.cwa.gz

      - name: Test with pytest
        run: |
          echo "########## NOTE ##########"
          echo "Windows access violation error can be safely ignored. See: https://github.com/jpype-project/jpype/issues/561"
          pytest tests
