name: cwa

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  cwa:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Compile java files
        run: |
          java -version
          javac src/actipy/*.java

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install pytest joblib

      - name: Download test files
        run: |
          wget -P tests/data/ https://wearables-files.ndph.ox.ac.uk/files/data/samples/ax3/tiny-sample.cwa.gz --quiet
          wget -P tests/data/ https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/read.csv.gz --quiet
          wget -P tests/data/ https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/lowpass.csv.gz --quiet
          wget -P tests/data/ https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/calib.csv.gz --quiet
          wget -P tests/data/ https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/nonwear.csv.gz --quiet
          wget -P tests/data/ https://wearables-files.ndph.ox.ac.uk/files/actipy/tests/data/resample.csv.gz --quiet
          cp tests/data/tiny-sample.cwa.gz tests/data/tiny-sample1.cwa.gz  # make copies for multiprocessing test
          cp tests/data/tiny-sample.cwa.gz tests/data/tiny-sample2.cwa.gz

      - name: Test with pytest
        run: |
          pytest tests/
