name: install

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  install:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Compile java files (Unix)
        if: runner.os != 'Windows'
        run: |
          set -e
          java -version
          javac src/actipy/*.java

      - name: Compile java files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          java -version
          javac src\actipy\*.java

      - name: Pip install this (Unix)
        if: runner.os != 'Windows'
        run: |
          set -e
          python -m pip install --upgrade pip
          python -m pip install .[dev,docs]

      - name: Pip install this (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          python -m pip install --upgrade pip
          python -m pip install .[dev,docs]
