name: install

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  install:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile java files
        run: |
          java -version
          javac src/actipy/*.java

      - name: Pip install this
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev,docs]
